"""Emit LaTeX tables for the Results chapter.

Reproduce: git checkout benchmark-2026-04-02 && python scripts/figures/make_tables.py
"""

from __future__ import annotations

from statistics import mean

from _style import (
    AGGREGATORS,
    CONDITIONS,
    FEDAVG_BYTES_PER_CLIENT_FP16,
    LABEL,
    ensure_res_dir,
    flatten_client_rounds,
    load_config,
    load_history,
    mean_per_round,
)


def _peak(f1):
    m = max(f1)
    return m, f1.index(m) + 1


def _fmt(x, p=3):
    return f"{x:.{p}f}"


def write_peak_final_table(path):
    rows = []
    for cond in CONDITIONS:
        f1 = mean_per_round(load_history(cond), "f1")
        peak, round_idx = _peak(f1)
        rows.append((cond, peak, round_idx, f1[-1]))

    with path.open("w", encoding="utf-8") as fh:
        fh.write("% Auto-generated by scripts/figures/make_tables.py; do not edit by hand.\n")
        fh.write("\\begin{table}[t]\n")
        fh.write("\\centering\n")
        fh.write("\\caption[Peak and final F1 per condition]{Peak F1, round of peak, and final-round F1 for each condition in the 2026-04-02 benchmark (\\texttt{data/2026-04-02}).}\n")
        fh.write("\\label{tab:peak-final-f1}\n")
        fh.write("\\begin{tabular}{lccc}\n")
        fh.write("\\toprule\n")
        fh.write("Condition & Peak F1 & Round of peak & Final F1 \\\\\n")
        fh.write("\\midrule\n")
        for cond, peak, r, final in rows:
            fh.write(f"{LABEL[cond]} & {_fmt(peak)} & {r} & {_fmt(final)} \\\\\n")
        fh.write("\\bottomrule\n")
        fh.write("\\end{tabular}\n")
        fh.write("\\end{table}\n")


def write_config_summary(path):
    cfg = load_config("flora_graph")
    keys = [
        ("model_id", "Backbone"),
        ("load_in_4bit", "Quantisation"),
        ("lora_rank", "LoRA rank"),
        ("lora_alpha", "LoRA alpha"),
        ("lora_dropout", "LoRA dropout"),
        ("num_rounds", "Federation rounds"),
        ("num_clients", "Clients"),
        ("local_epochs", "Local epochs"),
        ("learning_rate", "Learning rate"),
        ("max_train_samples", "Train samples per client"),
        ("__eval_set", "Eval set per client"),
        ("mia_n_members", "MIA members"),
        ("mia_n_nonmembers", "MIA non-members"),
        ("retrieval_limit", "Retrieval limit"),
        ("retrieval_depth", "Retrieval depth"),
        ("graph_backend", "Graph backend"),
    ]

    def render(v):
        if isinstance(v, list):
            return ", ".join(str(x) for x in v)
        if isinstance(v, bool):
            return "4-bit" if v else "16-bit"
        if isinstance(v, str) and "/" in v:
            return f"\\texttt{{{v}}}"
        return str(v)

    with path.open("w", encoding="utf-8") as fh:
        fh.write("% Auto-generated by scripts/figures/make_tables.py; do not edit by hand.\n")
        fh.write("\\begin{table}[t]\n")
        fh.write("\\centering\n")
        fh.write("\\caption[Benchmark hyper-parameter summary]{Benchmark hyper-parameters used for the 2026-04-02 run. Values are taken from \\texttt{data/2026-04-02/config\\_flora\\_graph.json}; other conditions share all values except \\texttt{retrieval\\_mode} and \\texttt{aggregation}.}\n")
        fh.write("\\label{tab:config-summary}\n")
        fh.write("\\begin{tabular}{ll}\n")
        fh.write("\\toprule\n")
        fh.write("Parameter & Value \\\\\n")
        fh.write("\\midrule\n")
        for k, name in keys:
            if k == "__eval_set":
                # max_eval_samples=1 in the archive is a degenerate value: the
                # client code computes cap_each = 1 // 2 = 0 and falls back to
                # the full stratified test split (src/federation/client.py:339).
                # Reporting the raw "1" would mislead the reader, so the table
                # shows the effective behaviour instead.
                fh.write(f"{name} & full stratified test split (380--726, mean 578) \\\\\n")
            elif k in cfg:
                fh.write(f"{name} & {render(cfg[k])} \\\\\n")
        fh.write("\\bottomrule\n")
        fh.write("\\end{tabular}\n")
        fh.write("\\end{table}\n")


def write_ablation_table(path):
    with path.open("w", encoding="utf-8") as fh:
        fh.write("% Auto-generated by scripts/figures/make_tables.py; do not edit by hand.\n")
        fh.write("\\begin{table}[t]\n")
        fh.write("\\centering\n")
        fh.write("\\caption[Flat vs RAG ablation]{Flat vs RAG ablation: peak and final F1 per aggregator, with the RAG minus flat delta. A positive delta means adding the graph-based signals helped.}\n")
        fh.write("\\label{tab:ablation-flat-vs-rag}\n")
        fh.write("\\begin{tabular}{lrrrrrr}\n")
        fh.write("\\toprule\n")
        fh.write("Aggregator & Peak flat & Peak RAG & $\\Delta$ peak & Final flat & Final RAG & $\\Delta$ final \\\\\n")
        fh.write("\\midrule\n")
        for agg in AGGREGATORS:
            f1_flat = mean_per_round(load_history(f"{agg}_flat"), "f1")
            f1_graph = mean_per_round(load_history(f"{agg}_graph"), "f1")
            pf, pg = max(f1_flat), max(f1_graph)
            ff, fg = f1_flat[-1], f1_graph[-1]
            fh.write(
                f"{agg.capitalize()} & {_fmt(pf)} & {_fmt(pg)} & "
                f"{_fmt(pg - pf)} & {_fmt(ff)} & {_fmt(fg)} & {_fmt(fg - ff)} \\\\\n"
            )
        fh.write("\\bottomrule\n")
        fh.write("\\end{tabular}\n")
        fh.write("\\end{table}\n")


def write_f1_per_round_table(path):
    """Per-round mean F1 across the three clients, all six conditions, with the
    per-column peak round emphasised in bold. The column order matches the
    Centralised/FedAvg/FLoRA grouping used elsewhere in the chapter."""
    cols = ["centralised_flat", "centralised_graph",
            "fedavg_flat", "fedavg_graph",
            "flora_flat", "flora_graph"]
    series = {c: mean_per_round(load_history(c), "f1") for c in cols}
    n_rounds = len(next(iter(series.values())))
    peak_round = {c: series[c].index(max(series[c])) for c in cols}

    with path.open("w", encoding="utf-8") as fh:
        fh.write("% Auto-generated by scripts/figures/make_tables.py; do not edit by hand.\n")
        fh.write("\\begin{table}[t]\n")
        fh.write("\\centering\n")
        fh.write("\\caption[Per-round F1 across all six conditions]{Per-round mean F1 across the three clients for every condition in the 2026-04-02 benchmark. The per-column peak round is emphasised in bold. Columns are grouped by aggregator (Centralised, FedAvg, FLoRA) with the two retrieval modes (flat, RAG) reported side by side.}\n")
        fh.write("\\label{tab:f1-per-round}\n")
        fh.write("\\small\n")
        fh.write("\\begin{tabular}{c rr rr rr}\n")
        fh.write("\\toprule\n")
        fh.write(" & \\multicolumn{2}{c}{Centralised} & \\multicolumn{2}{c}{FedAvg} & \\multicolumn{2}{c}{FLoRA} \\\\\n")
        fh.write("\\cmidrule(lr){2-3} \\cmidrule(lr){4-5} \\cmidrule(lr){6-7}\n")
        fh.write("Round & flat & RAG & flat & RAG & flat & RAG \\\\\n")
        fh.write("\\midrule\n")
        for r in range(n_rounds):
            cells = []
            for c in cols:
                val = _fmt(series[c][r])
                cells.append(f"\\textbf{{{val}}}" if r == peak_round[c] else val)
            fh.write(f"R{r+1} & " + " & ".join(cells) + " \\\\\n")
        fh.write("\\bottomrule\n")
        fh.write("\\end{tabular}\n")
        fh.write("\\end{table}\n")


def write_trilemma_summary_table(path):
    """One row per method, three trilemma columns (utility / privacy /
    efficiency). Sells the architecture by putting the headline numbers in a
    single read - but every cell traces back to the archive or to the
    BACKBONE_PARAMS constant in scripts/figures/_style.py."""
    rows = []
    for cond in ["centralised_flat", "centralised_graph",
                 "fedavg_flat", "fedavg_graph",
                 "flora_flat", "flora_graph"]:
        h = load_history(cond)
        f1 = mean_per_round(h, "f1")
        peak = max(f1)
        if cond.startswith("centralised"):
            mia_str = "N/A"
            comm_str = "N/A"
        else:
            mia_vals = mean_per_round(h, "mia_auc")
            mia_str = _fmt(sum(mia_vals) / len(mia_vals))
            if cond.startswith("flora"):
                # Real measured payload from archive (per-client per-round, MB).
                flora_bytes = h["comm_bytes_flora"][0][0]
                mb = flora_bytes / 1_000_000
                fedavg_mb = FEDAVG_BYTES_PER_CLIENT_FP16 / 1_000_000
                ratio = fedavg_mb / mb
                comm_str = f"{mb:.1f}~MB ({ratio:.0f}$\\times$ vs FedAvg)"
            else:
                # FedAvg: theoretical full-backbone broadcast at fp16.
                fedavg_gb = FEDAVG_BYTES_PER_CLIENT_FP16 / 1_000_000_000
                comm_str = f"{fedavg_gb:.1f}~GB (1$\\times$ baseline)"
        rows.append((LABEL[cond], _fmt(peak), mia_str, comm_str))

    with path.open("w", encoding="utf-8") as fh:
        fh.write("% Auto-generated by scripts/figures/make_tables.py; do not edit by hand.\n")
        fh.write("\\begin{table}[t]\n")
        fh.write("\\centering\n")
        fh.write("\\caption[Trilemma summary across methods]{Trilemma summary across the six benchmarked conditions. Utility is the per-condition peak F1 from Table~\\ref{tab:f1-per-round}; Privacy is the run-averaged threshold-based MIA AUC against the chance baseline of $0.5$; Efficiency is the per-client per-round payload, with the FedAvg figure being the McMahan-style fp16 backbone reference and the FLoRA figure being the measured Fernet-encrypted adapter delta from the archive. Centralised conditions have no federation boundary and therefore no MIA or comms cost.}\n")
        fh.write("\\label{tab:trilemma-summary}\n")
        fh.write("\\small\n")
        fh.write("\\begin{tabular}{lccl}\n")
        fh.write("\\toprule\n")
        fh.write("Method & Utility (peak F1) & Privacy (mean MIA AUC) & Efficiency (per-client per-round) \\\\\n")
        fh.write("\\midrule\n")
        for label, peak, mia, comm in rows:
            fh.write(f"{label} & {peak} & {mia} & {comm} \\\\\n")
        fh.write("\\bottomrule\n")
        fh.write("\\end{tabular}\n")
        fh.write("\\end{table}\n")


def main() -> None:
    out_dir = ensure_res_dir()
    write_peak_final_table(out_dir / "tab-peak-final-f1.tex")
    write_config_summary(out_dir / "tab-config-summary.tex")
    write_ablation_table(out_dir / "tab-ablation-flat-vs-rag.tex")
    write_f1_per_round_table(out_dir / "tab-f1-per-round.tex")
    write_trilemma_summary_table(out_dir / "tab-trilemma-summary.tex")
    print(f"Wrote tables to {out_dir}")


if __name__ == "__main__":
    main()
